name: 'Cached Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs:
  using: 'composite'
  steps:
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.NODE_VERSION}}
        
    - name: Install Dependencies
      run: npm ci
      shell: bash