name: Deploy for node and pm2
on: 
    workflow_call:
      inputs:
        APP_NAME:
          description: Name of the Application
          required: true
          type: string
        SERVER_PORT:
          description: Node Version Number
          required: true
          type: number
        DEPLOY_PATH:
          description: Path where the Project will be Deployed
          required: true
          type: string

      secrets:
        IP:
          required: true
        USERNAME:
          required: true
        PASSWORD:
          required: true
        SSH:
          required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
        # Download Files
      - name: Get build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files

      - name: ls Files
        run: ls -a

        # Deploy Files to Server with sftp
      - name: Deploy Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.USERNAME }}
            server: ${{ secrets.IP }}
            password: ${{ secrets.PASSWORD }}
            ssh_private_key: ${{ secrets.SSH }} 
            local_path: |
              './'
              '!node_modules'
            remote_path: ${{inputs.DEPLOY_PATH}}

        # Connecting to Server over SSH and cd to path for App, install dependencies and then restart service
      - name: Install Dependencies on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{inputs.PORT}}
          script: |
            cd /var/www/app
            npm ci
            pm2 delete '${{inputs.APP_NAME}}'
            pm2 start npm --name '${{inputs.APP_NAME}}' -- start
            pm2 save