name: Build Discord Bot
on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        description: Node Version Number
        required: true
        type: number

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Remove node_modules
      run: rm -r node_modules

    - name: ls Files
      run: ls -a
    
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "test.json"
        json: '{"token":"jsdaniell", "baseurl":"mypass"}'

      # Upload Files for other Jobs to download
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: ${{github.workspace}}