name: Build Discord Bot
on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        description: Node Version Number
        required: true
        type: number
    secrets:
      TOKEN:
        required: true
      BASEURL:
        required: true

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Remove .git
      run: rm -r .git

    - name: Remove .github
      run: rm -r .github

    - name: ls Files
      run: ls -a
    
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "config.json"
        json: '{"token": "${{secrets.TOKEN}}", "baseUrl": "${{secrets.BASEURL}}"}'

      # Upload Files for other Jobs to download
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: ${{github.workspace}}